name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.3
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.4
  rxdart: ^0.27.7
  flutter_lints: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
